#!/usr/bin/env bash

REGEX='.+\.slurm\.out'

if [[ $1 == "--delete" ]]; then
    find . -maxdepth 1 -regextype posix-extended -regex $REGEX -delete
elif [[ $1 != "" ]]; then
    echo -e "\e[4mUsage\e[0m: cleanjobs [options]"
    echo "-h / --help: Display this message"
    echo "--delete: Delete cluster logs rather than moving them"
else
    # Defaults to sorting under last modified date
    find . -maxdepth 1 -regextype posix-extended -regex $REGEX -exec bash -c 'TODAY=$(stat -c %y "$1" | cut -f 1 -d " "); mkdir -p cluster_logs/$TODAY; mv $1 cluster_logs/$TODAY' _ {} \;
fi
