#!/usr/bin/env bash

read -e -p "Cores: " -i "1" CPUS
read -e -p "Memory (G): " -i "16" MEM
read -e -p "Time (Hours): " -i "80" TIME
COMMAND=$@
read -e -p "Command: " -i "$COMMAND" COMMAND

name="${COMMAND/\.\//}"

CPUS="$CPUS" MEM="$MEM" TIME="$TIME" COMMAND="$COMMAND" perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' < ~/opt/slurm/customjob.slurm | sbatch --job-name="$name"
