#!/usr/bin/env bash

srun \
     -J=interactive \
     --nodes=1 \
     --cpus-per-task=2 \
     --mem=16G \
     --time=10:00:00 \
     --mail-user=$USER@umich.edu \
     --mail-type=NONE \
     --account=test \
     --partition=standard \
     --qos=interactive \
     --pty /bin/bash
