#!/usr/bin/env bash

# cat <(echo '--cluster' \

sbatch_call()
{
echo "sbatch" \
     "-J {cluster.job-name}" \
     "--mail-user=$USER@umich.edu" \
     "--mail-type=BEGIN,END,FAIL" \
     "--output=%x-%j.slurm.out" \
     "--nodes={cluster.nodes}" \
     "--cpus-per-task={cluster.cpus-per-task}" \
     "--mem={cluster.mem}" \
     "--time={cluster.time}" \
     "--account=test" \
     "--partition=standard" \
     "--qos=normal"
}

make_cluster_config()
{
    if [ -e cluster.json ]
    then
        echo ~/opt/snakemake/cluster.json
    else
        jq -s '.[0] * .[1]' ~/opt/snakemake/cluster.json cluster.json > ~/opt/snakemake/combined.json
        echo ~/opt/snakemake/combined.json
    fi
}

snakemake --latency-wait 60 --cluster-config $(make_cluster_config) --cluster "$(sbatch_call)" $@
