#!/usr/bin/env bash

# cat <(echo '--cluster' \

sbatch_call()
{
echo "sbatch" \
     "-J {cluster.job-name}" \
     "--mail-user=$USER@umich.edu" \
     "--mail-type=BEGIN,END,FAIL" \
     "--output=%x-%j.slurm.out" \
     "--nodes={cluster.nodes}" \
     "--cpus-per-task={cluster.cpus-per-task}" \
     "--mem={cluster.mem}" \
     "--time={cluster.time}" \
     "--account=test" \
     "--partition=standard" \
     "--qos=normal"
}
snakemake --latency-wait 60 --cluster-config cluster.json --cluster "$(sbatch_call)" $@
